### ISSUE TITLE
Encode Failed code 4 ,IOS7

### ISSUE THREAD

**Issue by salazarfelipe** [keenan/cordova-phonegap-audio-encode#1]
I have Encode Failed code 4 in IOS new version (IOS7), this plugin works perfectly in IOS6 but i dont know what happens with IOS7

**Comment by keenan** [comment]
Here you go.

The only changed file is
https://github.com/keenan/cordova-phonegap-audio-encode/blob/master/AudioEncode.m

**Comment by Perdiga** [comment]
how can i solve this code 4 problem??
