### ISSUE TITLE
PhoneGap 3.x

### ISSUE THREAD

**Issue by bjudson** [keenan/cordova-phonegap-audio-encode#4]
Has anyone updated this plugin for PhoneGap 3.x? I understand it has a new plugin architecture. This plugin has been a lifesaver, and I'm still using it on PhoneGap 2.9, but thinking about upgrading.

**Comment by keenan** [comment]
I moved away from this plugin to a simpler solution. I don't need to record in WAV and then compress. Doing it in two steps was a hack. That two step process, for me, caused the UI to hang for ~250ms during the compress step which made running animations jump. For my application it is better to just record directly into a minimal format. Here is how I did that:

note: This is the mod I made in Cordova 2.X but I imagine you could figure out how to patch this into 3.X easily

Step 1: add this to the startRecordingAudio method on SDVSound.m before `audioFile.recorder =`

```
    NSDictionary *recordSettings = [NSDictionary dictionaryWithObjectsAndKeys:
                                    [NSNumber numberWithInt: kAudioFormatMPEG4AAC], AVFormatIDKey,
                                    [NSNumber numberWithFloat:16000.0], AVSampleRateKey,
                                    [NSNumber numberWithInt: 1], AVNumberOfChannelsKey,
                                    nil];
```

Then I replaced:

> audioFile.recorder = [[CDVAudioRecorder alloc] initWithURL:audioFile.resourceURL settings:nil error:&error]; // Default PCM recording

With:

> audioFile.recorder = [[CDVAudioRecorder alloc] initWithURL:audioFile.resourceURL settings:recordSettings error:&error];

This records directly in M4A, mono in a relatively low fi (16K) format. For my application, which is just capturing words, not music this is just what I needed. 

Note: when you make this change I got an error until I changed the contained file to a M4A ( eg. it erred when trying to use these setting to record into a file named xxx.wav).

**Comment by bjudson** [comment]
Wow, that is so much better. I wonder why Cordova doesn't allow passing these settings in? Anyway, I will give it a shot; seems simple enough.

**Comment by bjudson** [comment]
I just wanted to follow up with one more change you left out, in case anyone else comes across this. `CDVSound.m` checks to make sure you're using a wav file. Simply changing this at the top of the file should prevent that:
`#define RECORDING_WAV @"wav"`

I changed it to:
`#define RECORDING_WAV @"m4a"`

Thanks again for pointing out this approach.

**Comment by kjakub** [comment]
@keenan ,@bjudson

Can you guys help me where i suppose to find SDVSound.m file and integrate it to plugin?

**Comment by quanghoc** [comment]
I cannot find SDVSound.m but found CDVCapture.m

I made changes as below but this is still not working. 
https://github.com/jhiswin/cordova-plugin-media-capture/commit/a305b2fd67fd764bb208ce142646a17dcc31f374

If I put .m4a filename, it gave ABORT error 1
If I use .wav, it works but then again, it's just wave format

Any idea?

**Comment by 1nsaneinc** [comment]
where do we find this SDVSound.m file please?

**Comment by 1nsaneinc** [comment]
OK nevermind! got it. 
cordova-plugin-media/src/ios/CDVSound.m
